/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.sample.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EnumType {
  RESIDENCE, OFFICE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EnumType\",\"namespace\":\"com.example.sample.avro\",\"symbols\":[\"RESIDENCE\",\"OFFICE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
